name: iOS CI/CD Workflow
on:
  push:
    branches:
      - TestActions
  pull_request:
    branches:
      - TestActions
jobs:
  build_and_test:
    name: Build and Test iOS Application
    runs-on: macos-latest
  steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: List top-level files in the repository to verify structure
      - name: List Top-level Directory Contents
        run: |
          ls -l  # List top-level files in the root directory



      # Step 3: List files inside the SourceCode folder to confirm correct structure
      - name: List files in SourceCode directory
        run: |
          ls -R SourceCode  # List files recursively in SourceCode folder

    

      # Step 5: Build the iOS App using the correct .xcodeproj
      - name: Build the iOS App
        run: |
          xcodebuild -project SourceCode/SwiftUIDemo.xcodeproj -scheme TestSwift-UICases-Demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=16.0' build



      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild -project SourceCode/SwiftUIDemo.xcodeproj -scheme TestSwift-UICases-Demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=16.0' test