name: iOS CI/CD Workflow
on:
  push:
    branches:
      - TestActions
  pull_request:
    branches:
      - TestActions
jobs:
  build_and_test:
    name: Build and Test iOS Application
    runs-on: macos-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build the iOS App
      run: >
        xcodebuild -workspace SwiftUIDemo.xcodeproj -scheme TestSwift-UICases-Demo
        -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone
        12,OS=16.0' build
    - name: Run Unit Tests
      run: >
        xcodebuild -workspace SwiftUIDemo.xcodeproj -scheme TestSwift-UICases-Demo
        -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone
        12,OS=16.0' test