name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

     - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_146.0.app

     - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project SwiftUIDemo.xcodeproj -scheme GitHubAction | xcpretty
          

        
