name: iOS starter workflow
'on':
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: List Top-level Directory Contents
        run: |
          ls -l  # List top-level files in the root directory

      - name: List files in SourceCode directory
        run: |
           ls -R SourceCode  # List files recursively in SourceCode folder

      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
      - name: Build Cleanup
        run: >
          xcodebuild clean -project SourceCode/SwiftUIDemo.xcodeproj -scheme SwiftUIDemo
          | xcpretty
      - name: Build Test
        run: >
          xcodebuild test -project SourceCode/SwiftUIDemo.xcodeproj -scheme SwiftUIDemo
          -destination 'platform=iOS   Simulator,name=iPhone 14,OS=16.2' |
          xcpretty -s
